apiVersion: v1
kind: Service
metadata:
  name: MYAPP
  namespace: default
spec:
  selector:
    app: MYAPP
  type: ClusterIP
  ports:
  - name: MYAPP
    port: 
    targetPort: 
    protocol: TCP
    nodePort: 