apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  namespace: default
spec:
  selector:
    app: nginx-start-probe02
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP