apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # 类属性键；每一个键都映射到一个简单的值
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  # 类文件键    aa \ 
  game.properties: |  ## 多行内容写法
    enemy.types=aliens,monsters
    player.maximum-lives=5   
 
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: v1
kind: Pod
metadata:
  name: "cm-pod"
  namespace: default
  labels:
    app: "cm-pod"
spec:
  volumes:
  - name: my-cm
    configMap: 
      name: game-demo ## 指定cm的名字
      # items: 
      #  - 
  containers:
  - name: cm-pod
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    env:
    - name: PLAY_LIVES
      valueFrom:
        configMapKeyRef:  ##来自于cm
          name: game-demo
          key: player_initial_lives
    volumeMounts:
    - name: my-cm
      mountPath: /app  ## 容器内的app文件夹是集群中 secret名叫db-user-pass的内容
