apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP