apiVersion: v1
kind: Pod
metadata:
  name: "pod-taint-02"
  namespace: default
  labels:
    app: "pod-taint-02"
spec:
  containers:
  - name: pod-taint-02
    image: "busybox"
    command: ["sleep","3600"]
  tolerations: ## 容忍
  - key: "haha"
    # operator: "Equal"
    # value: "666"
    effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  taint-haha
  namespace: default
  labels:
    app:  taint-haha
spec:
  selector:
    matchLabels:
      app: taint-haha
  replicas: 3
  template:
    metadata:
      labels:
        app:  taint-haha
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      initContainers:
      - name:  init-01 #request-cpu: 300m
        image:  "busybox"
        command: ["sleep","3600"] 
      - name:  init-02 #request-cpu: 100m
        image:  "busybox"
        command: ["sleep","3600"] 
      containers:  ## 哪个启动不了，后面的就不能启动
      - name:  taint-haha  #request-cpu: 200m
        image:  "busybox"
        command: ["sleep","3600"] 
      tolerations: ## 容忍
      - key: "haha"
        operator: "Exists"
        effect: "NoSchedule"
    