apiVersion: v1
data:
  my.cnf: |
    # Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    secure-file-priv= NULL
    skip-host-cache
    skip-name-resolve

    # Custom config should go here
    !includedir /etc/mysql/conf.d/
kind: ConfigMap
metadata:
  name: myconf